// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwyDd-Nc7PcnotDL7pHOFuTlEe8mQqpik',
    appId: '1:640291396160:web:2180a8fe44f80390b99da5',
    messagingSenderId: '640291396160',
    projectId: 'lastcrudtest',
    authDomain: 'lastcrudtest.firebaseapp.com',
    storageBucket: 'lastcrudtest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZEWhL1SIADd6Y7V8wLnuaqj32eNEqfA',
    appId: '1:640291396160:android:f89952da0b4ae44ab99da5',
    messagingSenderId: '640291396160',
    projectId: 'lastcrudtest',
    storageBucket: 'lastcrudtest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBXxney4krqy8AG5ET64uyAQysJNrUlzg',
    appId: '1:640291396160:ios:21fd15962f43dbd0b99da5',
    messagingSenderId: '640291396160',
    projectId: 'lastcrudtest',
    storageBucket: 'lastcrudtest.appspot.com',
    iosClientId: '640291396160-a2rl5npg3eqeqnb5cst2gjblebn1vgqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lasttimecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBXxney4krqy8AG5ET64uyAQysJNrUlzg',
    appId: '1:640291396160:ios:21fd15962f43dbd0b99da5',
    messagingSenderId: '640291396160',
    projectId: 'lastcrudtest',
    storageBucket: 'lastcrudtest.appspot.com',
    iosClientId: '640291396160-a2rl5npg3eqeqnb5cst2gjblebn1vgqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lasttimecrud',
  );
}
